name: Pull Requests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    secrets:
      CHARMHUB_TOKEN:
        required: false
    branches:
      - main

jobs:
  check-secret:
    runs-on: ubuntu-latest
    outputs:
      defined: ${{ steps.check.outputs.defined }}
    steps:
      - id: check
        env:
          CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}
        if: "${{ env.CHARMHUB_TOKEN != '' }}"
        run: echo "::set-output name=defined::true"
  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    needs:
      - check-secret
    if: needs.check-secret.outputs.defined == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.0.0
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  static-analysis:
    name: Static Analysis
    uses: canonical/observability/.github/workflows/_static-analysis.yaml@main
  linting:
    name: Linting
    uses: canonical/observability/.github/workflows/_linting.yaml@main
  unit-test:
    name: Unit Tests
    uses: canonical/observability/.github/workflows/_unit-tests.yaml@main
  integration-test:
    name: Integration Tests
    needs:
      - static-analysis
      - linting
      - unit-test
    uses: canonical/observability/.github/workflows/_integration-tests.yaml@main
